sudo: false
language: ruby

os:
  - linux
  - osx

env:
  - BADGE=linux
  - BADGE=osx

# hack to get some OS-specific badges
matrix:
  exclude:
    - os: linux
      env: BADGE=osx
    - os: osx
      env: BADGE=linux

before_install:
  - gem install bundler -v 1.15.4
  - bundle _1.15.4_ install
script:
   - g++ -v
   #- gem install bundle -v 1.15.4
   #- bundle _1.15_ install
   - bundle install
   - bundle exec rubocop --version
   - bundle exec rubocop -D .
   - bundle exec rspec --backtrace
   - cd SampleProjects/TestSomething
   - bundle install
   - bundle exec arduino_ci_remote.rb
